### ISSUE TITLE
Package magic

### ISSUE THREAD

**Issue by mithro** [litex-hub/litex-conda-eda#27] opened 2020-06-25 15:14 UTC
For the https://github.com/google/skywater-pdk I need https://github.com/RTimothyEdwards/magic and hence it would be good to get it packaged in conda.

**Comment by PiotrZierhoffer** [comment] 2020-06-26 13:34
https://github.com/litex-hub/litex-conda-eda/pull/28 - this is still WIP, have some troubles getting the proper configuration. Apparently magic doesn't want to compile without X (even with the relevant switch), and it seems it requires a very specific setup on host. Will continue this in few hours.

**Comment by PiotrZierhoffer** [comment] 2020-06-26 13:34
Make commands do not seem to return proper error codes for some reason

**Comment by PiotrZierhoffer** [comment] 2020-06-29 11:15
The current package builds, but tclmagic.so is not built as expected. I can't reproduce this locally, but still looking for the reason here

**Comment by PiotrZierhoffer** [comment] 2020-06-29 14:20
Found a problem with `ld` lookup. So the package builds fine. The next step - getting cairo to work, as Tim Edwards suggests you need it

**Comment by PiotrZierhoffer** [comment] 2020-06-29 19:09
Since it's merged, I close the issue. Let's open new ones if anything's wrong

**Closed by PiotrZierhoffer** 2020-06-29 19:09 UTC
